//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5MVCdemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NoteMarketPlaceEntities : DbContext
    {
        public NoteMarketPlaceEntities()
            : base("name=NoteMarketPlaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Download> Downloads { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<NoteCategory> NoteCategories { get; set; }
        public virtual DbSet<NoteReport> NoteReports { get; set; }
        public virtual DbSet<NoteReview> NoteReviews { get; set; }
        public virtual DbSet<NoteType> NoteTypes { get; set; }
        public virtual DbSet<Reference> References { get; set; }
        public virtual DbSet<SellNoteAttachment> SellNoteAttachments { get; set; }
        public virtual DbSet<SellNote> SellNotes { get; set; }
        public virtual DbSet<SystemConfiguration> SystemConfigurations { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<GetSellNoteDetails_Result> GetSellNoteDetails(Nullable<int> fK_Type, Nullable<int> fK_Category, Nullable<int> fK_Country, string fK_University, string fK_Course)
        {
            var fK_TypeParameter = fK_Type.HasValue ?
                new ObjectParameter("FK_Type", fK_Type) :
                new ObjectParameter("FK_Type", typeof(int));
    
            var fK_CategoryParameter = fK_Category.HasValue ?
                new ObjectParameter("FK_Category", fK_Category) :
                new ObjectParameter("FK_Category", typeof(int));
    
            var fK_CountryParameter = fK_Country.HasValue ?
                new ObjectParameter("FK_Country", fK_Country) :
                new ObjectParameter("FK_Country", typeof(int));
    
            var fK_UniversityParameter = fK_University != null ?
                new ObjectParameter("FK_University", fK_University) :
                new ObjectParameter("FK_University", typeof(string));
    
            var fK_CourseParameter = fK_Course != null ?
                new ObjectParameter("FK_Course", fK_Course) :
                new ObjectParameter("FK_Course", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSellNoteDetails_Result>("GetSellNoteDetails", fK_TypeParameter, fK_CategoryParameter, fK_CountryParameter, fK_UniversityParameter, fK_CourseParameter);
        }
    
        public virtual ObjectResult<GetSellerNotesDetail_Result> GetSellerNotesDetail(Nullable<int> fK_Type, Nullable<int> fK_Category, Nullable<int> fK_Country, string fK_University, string fK_Course)
        {
            var fK_TypeParameter = fK_Type.HasValue ?
                new ObjectParameter("FK_Type", fK_Type) :
                new ObjectParameter("FK_Type", typeof(int));
    
            var fK_CategoryParameter = fK_Category.HasValue ?
                new ObjectParameter("FK_Category", fK_Category) :
                new ObjectParameter("FK_Category", typeof(int));
    
            var fK_CountryParameter = fK_Country.HasValue ?
                new ObjectParameter("FK_Country", fK_Country) :
                new ObjectParameter("FK_Country", typeof(int));
    
            var fK_UniversityParameter = fK_University != null ?
                new ObjectParameter("FK_University", fK_University) :
                new ObjectParameter("FK_University", typeof(string));
    
            var fK_CourseParameter = fK_Course != null ?
                new ObjectParameter("FK_Course", fK_Course) :
                new ObjectParameter("FK_Course", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSellerNotesDetail_Result>("GetSellerNotesDetail", fK_TypeParameter, fK_CategoryParameter, fK_CountryParameter, fK_UniversityParameter, fK_CourseParameter);
        }
    
        public virtual ObjectResult<GetSellerNotesDetails_Result> GetSellerNotesDetails(Nullable<int> fK_Type, Nullable<int> fK_Category, Nullable<int> fK_Country, string fK_University, string fK_Course, Nullable<int> pageSize, Nullable<int> pageNumber, string search)
        {
            var fK_TypeParameter = fK_Type.HasValue ?
                new ObjectParameter("FK_Type", fK_Type) :
                new ObjectParameter("FK_Type", typeof(int));
    
            var fK_CategoryParameter = fK_Category.HasValue ?
                new ObjectParameter("FK_Category", fK_Category) :
                new ObjectParameter("FK_Category", typeof(int));
    
            var fK_CountryParameter = fK_Country.HasValue ?
                new ObjectParameter("FK_Country", fK_Country) :
                new ObjectParameter("FK_Country", typeof(int));
    
            var fK_UniversityParameter = fK_University != null ?
                new ObjectParameter("FK_University", fK_University) :
                new ObjectParameter("FK_University", typeof(string));
    
            var fK_CourseParameter = fK_Course != null ?
                new ObjectParameter("FK_Course", fK_Course) :
                new ObjectParameter("FK_Course", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSellerNotesDetails_Result>("GetSellerNotesDetails", fK_TypeParameter, fK_CategoryParameter, fK_CountryParameter, fK_UniversityParameter, fK_CourseParameter, pageSizeParameter, pageNumberParameter, searchParameter);
        }
    
        public virtual ObjectResult<NewGetSellerNotesDetails_Result> NewGetSellerNotesDetails(Nullable<int> fK_Type, Nullable<int> fK_Category, Nullable<int> fK_Country, string fK_University, string fK_Course, Nullable<int> pageSize, Nullable<int> pageNumber, string search, string rating)
        {
            var fK_TypeParameter = fK_Type.HasValue ?
                new ObjectParameter("FK_Type", fK_Type) :
                new ObjectParameter("FK_Type", typeof(int));
    
            var fK_CategoryParameter = fK_Category.HasValue ?
                new ObjectParameter("FK_Category", fK_Category) :
                new ObjectParameter("FK_Category", typeof(int));
    
            var fK_CountryParameter = fK_Country.HasValue ?
                new ObjectParameter("FK_Country", fK_Country) :
                new ObjectParameter("FK_Country", typeof(int));
    
            var fK_UniversityParameter = fK_University != null ?
                new ObjectParameter("FK_University", fK_University) :
                new ObjectParameter("FK_University", typeof(string));
    
            var fK_CourseParameter = fK_Course != null ?
                new ObjectParameter("FK_Course", fK_Course) :
                new ObjectParameter("FK_Course", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var ratingParameter = rating != null ?
                new ObjectParameter("Rating", rating) :
                new ObjectParameter("Rating", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NewGetSellerNotesDetails_Result>("NewGetSellerNotesDetails", fK_TypeParameter, fK_CategoryParameter, fK_CountryParameter, fK_UniversityParameter, fK_CourseParameter, pageSizeParameter, pageNumberParameter, searchParameter, ratingParameter);
        }
    
        public virtual ObjectResult<getDahboardData_Result> getDahboardData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDahboardData_Result>("getDahboardData");
        }
    
        public virtual ObjectResult<GetNotesUnderReviewData_Result> GetNotesUnderReviewData(string data)
        {
            var dataParameter = data != null ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNotesUnderReviewData_Result>("GetNotesUnderReviewData", dataParameter);
        }
    
        public virtual ObjectResult<GetMembersData_Result> GetMembersData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMembersData_Result>("GetMembersData");
        }
    
        public virtual ObjectResult<GetPublishedNotesData_Result> GetPublishedNotesData(string data)
        {
            var dataParameter = data != null ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPublishedNotesData_Result>("GetPublishedNotesData", dataParameter);
        }
    
        public virtual ObjectResult<GetRejectedNotesData_Result> GetRejectedNotesData(string data)
        {
            var dataParameter = data != null ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRejectedNotesData_Result>("GetRejectedNotesData", dataParameter);
        }
    
        public virtual ObjectResult<NewGetNotesUnderReviewData_Result> NewGetNotesUnderReviewData(string data)
        {
            var dataParameter = data != null ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NewGetNotesUnderReviewData_Result>("NewGetNotesUnderReviewData", dataParameter);
        }
    
        public virtual ObjectResult<GetMembersDetails_Result> GetMembersDetails(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMembersDetails_Result>("GetMembersDetails", iDParameter);
        }
    
        public virtual ObjectResult<NewGetMembersDetails_Result> NewGetMembersDetails(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NewGetMembersDetails_Result>("NewGetMembersDetails", iDParameter);
        }
    
        public virtual ObjectResult<GetDownloadedNotesData_Result> GetDownloadedNotesData(Nullable<int> noteID, Nullable<int> sellerID, Nullable<int> downloaderID)
        {
            var noteIDParameter = noteID.HasValue ?
                new ObjectParameter("NoteID", noteID) :
                new ObjectParameter("NoteID", typeof(int));
    
            var sellerIDParameter = sellerID.HasValue ?
                new ObjectParameter("SellerID", sellerID) :
                new ObjectParameter("SellerID", typeof(int));
    
            var downloaderIDParameter = downloaderID.HasValue ?
                new ObjectParameter("DownloaderID", downloaderID) :
                new ObjectParameter("DownloaderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDownloadedNotesData_Result>("GetDownloadedNotesData", noteIDParameter, sellerIDParameter, downloaderIDParameter);
        }
    
        public virtual ObjectResult<NewGetMembersData_Result> NewGetMembersData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NewGetMembersData_Result>("NewGetMembersData");
        }
    
        public virtual ObjectResult<GetCountryData_Result> GetCountryData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountryData_Result>("GetCountryData");
        }
    
        public virtual ObjectResult<GetCategoryData_Result> GetCategoryData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCategoryData_Result>("GetCategoryData");
        }
    
        public virtual ObjectResult<GetNoteTypeData_Result> GetNoteTypeData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNoteTypeData_Result>("GetNoteTypeData");
        }
    
        public virtual ObjectResult<NewGetDashboadrd_Result> NewGetDashboadrd(Nullable<int> data)
        {
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NewGetDashboadrd_Result>("NewGetDashboadrd", dataParameter);
        }
    }
}
